development:
  adapter: postgresql
  database: yelp_map_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: yelp_map_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: yelp_map
  pool: 5
  timeout: 5000